import "./style.css";
import "./assets/css/prism.css";
import "./src/intersectionObserver";
import "./src/themeSwitcher";
import "./src/prism.js";
import "./src/counter";
import "./src/navmenu";
import "./src/clipboard";
import "./src/tabs";
